version: '3.8'
services:
  nginx:
    ports:
      - '80:80'
  server:
    build:
      context: './'
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node src/index.js
