version: '3.8'
services:
  server:
    build:
      context: './'
      args:
        NODE_ENV: development
    ports:
      - '3001:3001'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
