version: '3.8'
services:
  nginx:
    ports:
      - '3030:80'
  server:
    build:
      context: './'
      args:
        NODE_ENV: development
    # ports:
    #   - '3001:3001'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=example
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
